name: Test GitHub Workflow contexts

on: [push, issues, pull_request, release, workflow_dispatch]
permissions: write-all

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Pnpm install
        run: |
          pnpm i

      - name: Get contexts
        run: |
          node ./contexts.js ${{ github }}
