name: Test GitHub Workflow contexts

on: [push, issues, pull_request, release, workflow_dispatch]
permissions: write-all

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: tools/package-lock.json

      - name: Npm install
        run: |
          cd tools && npm i && cd ..

      - name: Get tags By simeple-git
        run: |
          node ./tools/contexts.js
