name: Build Push Changes
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get short commit hash
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

  upload:
    needs: build
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Upload development build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TODAY: ${{ steps.date.outputs.date }}
      - name: Print date
        run: echo "$TODAY"
