name: Test Connectivity
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ping cr.liplum.net
        run: |
          ping cr.liplum.net

      - name: check cr.liplum.net
        run: |
          curl https://cr.liplum.net
          curl https://cr.liplum.net/v2